
title: Planar Network
email: info@planar.network
description: >-
  Public transit technology, blockchain travel tickets.
baseurl: ""
url: "https://planar.network/"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-minifier
exclude:
- README.md
- vendor/
- CNAME
permalink: /posts/:title
excerpt_separator: <!--more-->
autoprefixer:
  browsers:
  - last 2 versions
sass:
  style: compressed
